### ISSUE TITLE
XPath select for parent node prevalue

### ISSUE THREAD

**Issue by rasmuseeg** [jezzipin/jezzipin.TagliatelleTagManager#4]
Hi, i would like the option, to use xpath to select parent node.
The reason for this is that i have a multiple language site, and tag are in different languages.

**Comment by JasonEspin** [comment]
Hi Rasmus,

Could you give me an example of the sort of Xpath query you would like to
perform and how you envisage this working? XPATH was never a consideration
in the original version as its a bit of a dated way of doing things (and
I've never used it) but I'm happy to add in support for it. May take me a
while though.

Cheers,

Jason

**Comment by rasmuseeg** [comment]
Thanks for your response.

When i think about a use case for XPATH i would query for site root node, and then select the first child of document type `Tags`.

Here is a sample based on Umbraco.MultiNodeTreePicker
![image](https://cloud.githubusercontent.com/assets/1511208/19264652/e9bd34ba-8fa1-11e6-9c17-191aae5bd7a6.png)

**Comment by JasonEspin** [comment]
Okay, I've had a quick look and I may be able to use the existing treesource prevalue editor in Umbraco for parent selection rather than the custom editor currently in place. How this will then work with the WebApi request that is performed behind the scenes as part of my plugin I do not know but I will try and take a look tonight and let you know if I am able to add this functionality in a release or if it will need to be left out.

**Comment by rasmuseeg** [comment]
Hi Jason, 

I found the following article which might be helpful, it takes an xpath and variables and returns single typed content or content .

https://our.umbraco.org/documentation/reference/querying/umbracohelper/#typedcontentatxpath-string-xpath
